[theme]
base = "dark"               # Força o tema claro, ignorando o sistema do usuário
primaryColor = "#DD4F05"     # Cor laranja dos seus botões principais
backgroundColor = "linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(235,245,245,1) 100%);"  # Cor de fundo da página

secondaryBackgroundColor = "#" # Cor de fundo da barra lateral e inputs
textColor = ""        # Cor do texto
font = "sans serif"
#rgb(2, 19, 19)
