[theme]
base = "dark"               # Força o tema claro, ignorando o sistema do usuário
primaryColor = "#DD4F05"     # Cor laranja dos seus botões principais
backgroundColor = ""  # Cor de fundo da página
secondaryBackgroundColor = "#F0F2F6" # Cor de fundo da barra lateral e inputs
textColor = "#31333F"        # Cor do texto
font = "sans serif"
